import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import mingcuteData from '@iconify-json/mingcute/icons.json' with { type: 'json' };

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const scanDirs = [path.join(rootDir, 'src'), path.join(rootDir, 'shared')];
const outputPath = path.join(rootDir, 'src', 'lib', 'generated', 'icon-collections.ts');

const iconSets = {
  mingcute: mingcuteData,
};

async function listSourceFiles(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        return listSourceFiles(entryPath);
      }
      return /\.(js|jsx|mjs|ts|tsx)$/.test(entry.name) ? [entryPath] : [];
    }),
  );
  return files.flat();
}

function collectIconNames(source) {
  const namesByPrefix = new Map();
  const matches = source.matchAll(/\b([a-z0-9-]+):([a-z0-9-]+)\b/g);
  for (const [, prefix, name] of matches) {
    if (!(prefix in iconSets)) {
      continue;
    }
    if (!namesByPrefix.has(prefix)) {
      namesByPrefix.set(prefix, new Set());
    }
    namesByPrefix.get(prefix).add(name);
  }
  return namesByPrefix;
}

function buildCollections(namesByPrefix) {
  const collections = [];
  for (const [prefix, names] of [...namesByPrefix.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const iconSet = iconSets[prefix];
    const icons = {};
    for (const name of [...names].sort()) {
      const icon = iconSet.icons[name];
      if (!icon) {
        throw new Error(`Missing icon "${prefix}:${name}" in installed icon set.`);
      }
      icons[name] = icon;
    }
    collections.push({
      prefix,
      width: iconSet.width,
      height: iconSet.height,
      icons,
    });
  }
  return collections;
}

function serializeCollections(collections) {
  const json = JSON.stringify(collections, null, 2);
  return `import type { IconifyJSON } from '@iconify/react';\n\n// Generated by scripts/generate-icons.mjs\nexport const iconCollections: IconifyJSON[] = ${json};\n`;
}

const sourceFiles = (await Promise.all(scanDirs.map((dir) => listSourceFiles(dir)))).flat();
const sourceContents = await Promise.all(sourceFiles.map((file) => fs.readFile(file, 'utf8')));
const mergedNames = sourceContents.reduce((acc, source) => {
  const namesByPrefix = collectIconNames(source);
  for (const [prefix, names] of namesByPrefix.entries()) {
    if (!acc.has(prefix)) {
      acc.set(prefix, new Set());
    }
    for (const name of names) {
      acc.get(prefix).add(name);
    }
  }
  return acc;
}, new Map());

const collections = buildCollections(mergedNames);
await fs.mkdir(path.dirname(outputPath), { recursive: true });
await fs.writeFile(outputPath, serializeCollections(collections));

console.log(`Generated ${collections.length} icon collection(s) at ${outputPath}`);
